apiVersion: apps/v1
kind: Deployment
metadata:
  name: usuarios-backend-deployment
  labels:
    app: usuarios-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: usuarios-backend
  template:
    metadata:
      labels:
        app: usuarios-backend
    spec:
      containers:
      - name: usuarios-backend
        image: luismiguel13/prueba1:1.0
        ports:
        - containerPort: 5000
        env:
        - name: MYSQL_DB_HOST
          value: U_ComerceDB
        - name: MYSQL_DB_PORT
          value: "3306"
        - name: MYSQL_DB_USERNAME
          value: root
        - name: MYSQL_DB_PASSWORD
          value: "1234"
---
apiVersion: v1
kind: Service
metadata:
  name: usuarios-backend-service
spec:
  type: NodePort
  selector:
    app: usuarios-backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30000