apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-usuarios-deployment
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-usuarios
  template:
    metadata:
      labels:
        app: mysql-usuarios
    spec:
      containers:
      - name: mysql
        image: mysql:8.0.27
        ports:
        - containerPort: 3306
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: "1234"
          - name: MYSQL_DATABASE
            value: U_ComerceDB
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-usuarios-service  
spec:
  type: ClusterIP
  selector:
    app: mysql-usuarios
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306