version: '3.9'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: U_CommerceBD
      MYSQL_USER: root
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - '3306:3306'
  api:
    build: .
    ports:
      - '5000:5000'
    depends_on:
      - db
    environment:
      MYSQL_HOST: localhost
      MYSQL_USER: root
      MYSQL_PASSWORD: 1234
      MYSQL_DB: U_CommerceBD