# Generated by Django 4.1.2 on 2022-10-24 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='lenguage',
            new_name='lang',
        ),
    ]
