# Generated by Django 4.1.3 on 2022-11-01 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoredis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='codigo',
            field=models.ImageField(max_length=200, upload_to=''),
        ),
    ]
